'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
if(process.env.GCLOUD_PROJECT!=='demo-technominds'||!/^127\.0\.0\.1:\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Disposable demo emulator required.');
const {fakeJudge0}=require('./testing/fake-judge0');let provider,functions,db;
const req=(visitorId='visitor',ip='198.51.100.12',data={})=>({data:{visitorId,language:'javascript',sourceCode:'OPAQUE_PHASE23_SOURCE',stdin:'OPAQUE_PHASE23_STDIN',...data},rawRequest:{socket:{remoteAddress:ip},headers:{}}});
test.before(async()=>{provider=await fakeJudge0();Object.assign(process.env,provider.env,{CODE_IP_RUNS_PER_MINUTE:'20'});functions=require('../functions/entry');db=require('../functions/node_modules/firebase-admin').firestore();});test.after(async()=>provider?.close());
test('actual callable persists only hash/limited result and capability hash, not code/stdin/key',async()=>{const r=await functions.submitCodeExecution.run(req());const row=(await db.doc('code_execution_runs/'+r.runId).get()).data();assert.equal(row.resultTokenHash.length,64);assert(!JSON.stringify(row).includes('OPAQUE_PHASE23_SOURCE'));assert(!JSON.stringify(row).includes('OPAQUE_PHASE23_STDIN'));assert(!('resultToken'in row));assert.equal(row.sourceHash.length,64);assert.equal(row.expiresAt.toMillis()>Date.now(),true);});
test('same NAT and unknown IP cannot obtain results without capability; capability holder can retrieve',async()=>{const r=await functions.submitCodeExecution.run(req('owner'));for(const ip of ['198.51.100.12',''])await assert.rejects(functions.getCodeExecutionResult.run(req('attacker',ip,{runId:r.runId})),e=>e.code==='permission-denied');assert.equal((await functions.getCodeExecutionResult.run(req('owner','',{runId:r.runId,resultToken:r.resultToken}))).stdout,'hello');});
test('expired and legacy IP-owned results are not accessible',async()=>{const r=await functions.submitCodeExecution.run(req('expiry'));await db.doc('code_execution_runs/'+r.runId).update({expiresAt:require('../functions/node_modules/firebase-admin').firestore.Timestamp.fromMillis(Date.now()-1)});await assert.rejects(functions.getCodeExecutionResult.run(req('expiry',undefined,{runId:r.runId,resultToken:r.resultToken})),e=>e.code==='not-found');await db.doc('code_execution_runs/'+r.runId).update({resultTokenHash:require('../functions/node_modules/firebase-admin').firestore.FieldValue.delete()});await assert.rejects(functions.getCodeExecutionResult.run(req('expiry',undefined,{runId:r.runId,resultToken:r.resultToken})),e=>e.code==='permission-denied');});
test('transactional shared-IP limiter survives parallel rotating visitor IDs and spoofed XFF',async()=>{const ip='198.51.100.88';let accepted=0;const results=await Promise.all(Array.from({length:24},(_,i)=>{const r=req('rotate'+i,ip);r.rawRequest.headers['x-forwarded-for']='203.0.113.'+i;return functions.submitCodeExecution.run(r).then(()=>{accepted++;return'success';},e=>e.code);}));assert(accepted<=20);assert(results.includes('resource-exhausted'));const rateRows=await db.collection('_rate_limits').get();assert(rateRows.docs.some(d=>d.data().action==='code-run-public-ip'&&d.data().count===20));assert(!results.includes('internal'));});

test('code_execution_runs stays unreadable and unwritable from anonymous or verified browser Admin',async()=>{const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc}=require('firebase/firestore');const [host,port]=process.env.FIRESTORE_EMULATOR_HOST.split(':');const env=await initializeTestEnvironment({projectId:'demo-technominds',firestore:{host,port:Number(port)}});try{for(const context of [env.unauthenticatedContext(),env.authenticatedContext('runner-browser-admin',{admin:true,email_verified:true})]){const ref=doc(context.firestore(),'code_execution_runs/random');await assertFails(getDoc(ref));await assertFails(setDoc(ref,{stdout:'forged'}));}}finally{await env.cleanup();}});
