'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const policy=require('../functions/lib/code-runner-policy'),{harness}=require('./testing/code-runner-harness'),{fakeJudge0,accepted}=require('./testing/fake-judge0');
async function withProvider(scenario,fn,env={}){const p=await fakeJudge0(scenario);try{return await fn(harness({env:{...p.env,...env}}),p);}finally{await p.close();}}
const deny=e=>e.code==='unavailable';
for(const url of ['http://127.0.0.1','http://localhost','http://[::1]','http://169.254.169.254','http://metadata.google.internal','http://10.0.0.1','http://172.16.0.1','http://192.168.1.1','http://100.64.0.1','https://[fc00::1]','https://[fe80::1]','https://[::ffff:127.0.0.1]','https://user:pass@ce.judge0.com',' https://ce.judge0.com','https://ce.judge0.com\n','https://ce.judge0.com\\@evil.test','https://%63e.judge0.com','https://ce.judge0.com:8443','https://evil.test','https://ce.judge0.com/?destination=x'])test('endpoint rejects '+JSON.stringify(url),()=>assert.throws(()=>policy.codeRunnerConfig({JUDGE0_BASE_URL:url})));
test('explicit custom HTTPS origin/prefix works; private self-host requires two deliberate flags',()=>{assert.equal(policy.codeRunnerConfig({JUDGE0_BASE_URL:'https://runner.example.test/api',JUDGE0_ALLOWED_ORIGINS:'https://runner.example.test'}).baseUrl,'https://runner.example.test/api');assert.throws(()=>policy.codeRunnerConfig({JUDGE0_BASE_URL:'http://127.0.0.1:2356',JUDGE0_ALLOWED_ORIGINS:'http://127.0.0.1:2356'}));assert.equal(policy.codeRunnerConfig({JUDGE0_BASE_URL:'http://127.0.0.1:2356',JUDGE0_ALLOWED_ORIGINS:'http://127.0.0.1:2356',JUDGE0_ALLOW_PRIVATE_ENDPOINT:'true'}).allowPrivate,true);assert.equal(policy.codeRunnerConfig({JUDGE0_BASE_URL:'http://localhost:2356',JUDGE0_ALLOWED_ORIGINS:'http://localhost:2356',JUDGE0_ALLOW_PRIVATE_ENDPOINT:'true'}).allowPrivate,true);});
test('DNS private/link-local answers fail before submission',async()=>{const c=policy.codeRunnerConfig({});for(const address of ['127.0.0.1','10.0.0.1','169.254.169.254','fc00::1','fe80::1','::ffff:7f00:1'])await assert.rejects(policy.validateEndpointAddresses(c,async()=>[{address}]));await policy.validateEndpointAddresses(c,async()=>[{address:'203.0.113.1'}]);});
for(const header of ['Host','Cookie','Content-Type','X-Forwarded-For','Proxy-Authorization','x\r\nInjected','bad:header'])test('unsafe header rejected '+JSON.stringify(header),()=>assert.throws(()=>policy.codeRunnerConfig({JUDGE0_API_KEY_HEADER:header})));
test('key CRLF and RapidAPI host injection fail closed; valid key header is private config',()=>{assert.throws(()=>policy.codeRunnerConfig({JUDGE0_API_KEY:'secret\r\nx:y'}));assert.throws(()=>policy.codeRunnerConfig({JUDGE0_RAPIDAPI_HOST:'good.test\nwrong'}));assert.equal(policy.codeRunnerConfig({JUDGE0_API_KEY_HEADER:'Authorization',JUDGE0_API_KEY:'Bearer synthetic'}).apiKey,'Bearer synthetic');});
for(const raw of ['ع'.repeat(40000),'😀'.repeat(20000),'你好'.repeat(20000)])test('byte-safe bounded Unicode '+Buffer.byteLength(raw),()=>{const result=policy.limitedOutput(raw,32768);assert(Buffer.byteLength(result)<=32768);assert(!result.includes('\ufffd'));assert(result.endsWith('تم اختصار المخرجات'));});
test('bounded response reader cancels oversized chunked body before parse; invalid/deep/unexpected JSON is contained',async()=>{let cancelled=false;const r=new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(1025));},cancel(){cancelled=true;}}));await assert.rejects(policy.boundedJson(r,1024));assert(cancelled);for(const s of ['{bad','[]','null'])await assert.rejects(policy.boundedJson(new Response(s),1024));const deep=JSON.parse('['.repeat(1000)+'0'+']'.repeat(1000));await assert.rejects(policy.boundedJson(new Response(JSON.stringify({status:deep})),10000).then(policy.statusId));});
for(const language of [63,'shell','bash','../../x',{},'x'.repeat(10000)])test('language key allowlist rejects '+String(language).slice(0,25),async()=>{let calls=0;const h=harness({fetchImpl:async()=>{calls++;throw Error('network');}});await assert.rejects(h.functions.submitCodeExecution(h.request({language})),e=>e.code==='invalid-argument');assert.equal(calls,0);});
for(const language of ['python','javascript','typescript','c','cpp','java','csharp','go','php','ruby','rust','kotlin'])test('supported '+language+' uses fixed ID and all explicit isolation limits',async()=>withProvider({},async(h,p)=>{const r=await h.functions.submitCodeExecution(h.request({language}));assert.equal(r.status,'Accepted');const body=p.requests.find(x=>x.method==='POST').body;assert(Number.isInteger(body.language_id));assert.deepEqual({network:body.enable_network,processes:body.max_processes_and_or_threads,time:body.enable_per_process_and_thread_time_limit,memory:body.enable_per_process_and_thread_memory_limit,file:body.max_file_size},{network:false,processes:128,time:false,memory:false,file:1024});}));
test('source/stdin remain opaque JSON; cannot control destination, headers or route',async()=>withProvider({},async(h,p)=>{const source="'\"` ${x} \u0000 عربى\r\n $(touch /tmp/never) ; bash <script>";const r=await h.functions.submitCodeExecution(h.request({sourceCode:source,stdin:source,baseUrl:'http://evil.test',apiKey:'attacker',language_id:46}));const post=p.requests.find(x=>x.method==='POST');assert.equal(post.body.source_code,source);assert.equal(post.body.stdin,source);assert.equal(post.body.language_id,63);assert.equal(post.url,'/submissions?base64_encoded=false&wait=false');const stored=h.records.get('code_execution_runs/'+r.runId);assert(!JSON.stringify(stored).includes(source));assert(!('sourceCode'in stored||'stdin'in stored||'resultToken'in stored));assert.equal(stored.sourceHash.length,64);}));
test('maximum code/stdin accepted, excess bytes rejected before any network',async()=>withProvider({},async(h,p)=>{await h.functions.submitCodeExecution(h.request({sourceCode:'x'.repeat(65536),stdin:'x'.repeat(16384)}));const n=p.requests.length;for(const patch of [{sourceCode:'x'.repeat(65537)},{stdin:'ع'.repeat(8193)}])await assert.rejects(h.functions.submitCodeExecution(h.request(patch)),e=>e.code==='invalid-argument');assert.equal(p.requests.length,n);}));
for(const token of ['../secret','x?path=evil','x/../../secret','x'.repeat(101),{},'https://evil.test'])test('remote token rejected '+String(token).slice(0,22),async()=>withProvider({submit:{token}},async(h,p)=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert(!p.requests.some(x=>x.method==='GET'&&x.url.startsWith('/submissions/')));}));
for(const result of [{status:{id:0}},{status:{id:999}},{status:{id:'3'}},{stdout:'no status'}, {status:[]}])test('remote invalid status '+JSON.stringify(result),async()=>withProvider({result},async h=>assert.rejects(h.functions.submitCodeExecution(h.request()),deny)));
test('bounded hostile result fields and metrics; secrets not returned/persisted/health',async()=>withProvider({result:{...accepted,stdout:'ع'.repeat(20000),stderr:'😀'.repeat(4000),compile_output:'x'.repeat(35000),message:'PHASE23_FAKE_KEY '+'x'.repeat(35000),time:{bad:true},memory:-100,exit_code:'rm -rf'}},async(h,p)=>{const r=await h.functions.submitCodeExecution(h.request());for(const k of ['stdout','stderr','compileOutput','message'])assert(Buffer.byteLength(r[k])<=32768);assert.equal(r.time,'');assert.equal(r.memory,0);assert.equal(r.exitCode,null);assert(!JSON.stringify(r).includes('PHASE23_FAKE_KEY'));assert(r.message.includes('[REDACTED]'));assert(!JSON.stringify([...h.records.values()]).includes('PHASE23_FAKE_KEY'));const health=await h.functions.getPlatformHealth();assert(!JSON.stringify(health).includes('PHASE23_FAKE_KEY'));assert(!JSON.stringify(health).includes(p.origin));assert(p.requests.every(x=>x.headers['x-auth-token']==='PHASE23_FAKE_KEY'));},{JUDGE0_API_KEY:'PHASE23_FAKE_KEY'}));
test('oversized provider reply and invalid JSON are generic unavailable, not stored',async()=>{for(const body of ['{bad',JSON.stringify({...accepted,stdout:'x'.repeat(200000)})])await withProvider({handle:({res,row})=>{if(row.method==='POST'){res.end(body);return true;}}},async h=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert.equal(h.records.size,0);});});
test('provider config mismatch fails before source transmission; cached checks do not add per-run Firebase reads',async()=>{await withProvider({capabilities:{max_max_processes_and_or_threads:16}},async(h,p)=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert(!p.requests.some(x=>x.method==='POST'));});await withProvider({},async(h,p)=>{await h.functions.submitCodeExecution(h.request());await h.functions.submitCodeExecution(h.request());assert.equal(p.requests.filter(x=>x.url==='/config_info').length,1);});});
for(const status of [400,429,500])test('provider submit '+status+' does not duplicate execution',async()=>withProvider({submitStatus:status},async(h,p)=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert.equal(p.requests.filter(x=>x.method==='POST').length,1);}));
test('stuck pending has exactly bounded polling and no extra submission',async()=>withProvider({result:{status:{id:1,description:'In Queue'}}},async(h,p)=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert.equal(p.requests.filter(x=>x.url.startsWith('/submissions/')).length,40);assert.equal(p.requests.filter(x=>x.method==='POST').length,1);}));
test('400 fields rejection retries fixed plain route; token-route 404 allows only one sync compatibility retry',async()=>{await withProvider({handle:({row,res})=>{if(row.url.includes('&fields=')){res.statusCode=400;res.end('{}');return true;}}},async(h,p)=>{await h.functions.submitCodeExecution(h.request());assert(p.requests.some(x=>x.url==='/submissions/test-token?base64_encoded=false'));});await withProvider({handle:({row,res})=>{if(row.method==='GET'){res.statusCode=404;res.end('{}');return true;}if(row.url.includes('wait=true')){res.end(JSON.stringify(accepted));return true;}}},async(h,p)=>{await h.functions.submitCodeExecution(h.request());assert.equal(p.requests.filter(x=>x.method==='POST').length,2);});});
test('poll 429/500 never duplicates source as synchronous retry',async()=>{for(const status of [429,500])await withProvider({handle:({row,res})=>{if(row.method==='GET'){res.statusCode=status;res.end('{}');return true;}}},async(h,p)=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert.equal(p.requests.filter(x=>x.method==='POST').length,1);});});
test('307/302 redirects on config/submission/poll/sync cannot leak key or source',async()=>{let reached=0;const target=http.createServer((req,res)=>{reached++;res.end(JSON.stringify(accepted));});await new Promise(r=>target.listen(0,'127.0.0.1',r));try{for(const phase of ['config','submit','poll','sync'])for(const status of [302,307])await withProvider({redirectConfig:phase==='config',handle:({row,res})=>{const at=phase==='config'&&row.url==='/config_info'||phase==='submit'&&row.method==='POST'||phase==='poll'&&row.url.startsWith('/submissions/')||phase==='sync'&&row.url.includes('wait=true');if(at){res.writeHead(status,{Location:`http://127.0.0.1:${target.address().port}/sink`});res.end();return true;}if(phase==='sync'&&row.method==='GET'){res.statusCode=404;res.end('{}');return true;}}},async h=>{await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);assert.equal(reached,0);},{JUDGE0_API_KEY:'FAKE_SECRET'});}finally{target.closeAllConnections();await new Promise(r=>target.close(r));}});
test('rotating visitor IDs cannot bypass shared peer-IP ceiling; spoofed header is not trusted',async()=>withProvider({},async(h,p)=>{for(let i=0;i<20;i++){const req=h.request({visitorId:'rotating'+i});req.rawRequest.headers['x-forwarded-for']='203.0.113.'+i;await h.functions.submitCodeExecution(req);}const req=h.request({visitorId:'extra'});await assert.rejects(h.functions.submitCodeExecution(req),e=>e.code==='resource-exhausted');assert.equal(p.requests.filter(x=>x.method==='POST').length,20);},{CODE_IP_RUNS_PER_MINUTE:'20'}));
test('identity limit and unknown peer fail conservatively; classroom visitors have separate identity budgets',async()=>withProvider({},async(h,p)=>{for(let i=0;i<6;i++)await h.functions.submitCodeExecution(h.request());await assert.rejects(h.functions.submitCodeExecution(h.request()),e=>e.code==='resource-exhausted');await h.functions.submitCodeExecution(h.request({visitorId:'classmate'}));const missing=h.request({visitorId:'no-peer'},'');await h.functions.submitCodeExecution(missing);assert.equal(h.rates.at(-1).ip,'unknown');assert.equal(p.requests.filter(x=>x.method==='POST').length,8);}));
test('per-instance concurrent runs bounded; semaphore released on failed provider requests',async()=>{let release;const wait=new Promise(r=>release=r);let submitted=0;const h=harness({fetchImpl:async(url)=>{if(url.endsWith('/config_info'))return new Response(JSON.stringify(require('./testing/fake-judge0').capabilities));submitted++;await wait;return new Response(JSON.stringify(accepted));}});const jobs=Array.from({length:4},(_,i)=>h.functions.submitCodeExecution(h.request({visitorId:'parallel'+i})));while(submitted<4)await new Promise(r=>setImmediate(r));await assert.rejects(h.functions.submitCodeExecution(h.request({visitorId:'fifth'})),e=>e.code==='resource-exhausted');release();await Promise.all(jobs);await h.functions.submitCodeExecution(h.request({visitorId:'after'}));});
test('result capability prevents same NAT/unknown/visitor impersonation; expiry is enforced',async()=>withProvider({},async h=>{const r=await h.functions.submitCodeExecution(h.request());assert.match(r.runId,/^[a-f0-9-]{36}$/);assert.equal(r.resultToken.length,43);for(const patch of [{runId:r.runId},{runId:r.runId,resultToken:'x'.repeat(43),visitorId:'visitor'}])await assert.rejects(h.functions.getCodeExecutionResult(h.request(patch)),e=>e.code==='permission-denied');assert.equal((await h.functions.getCodeExecutionResult(h.request({runId:r.runId,resultToken:r.resultToken},'unknown'))).stdout,'hello');const row=h.records.get('code_execution_runs/'+r.runId);row.expiresAt={toMillis:()=>Date.now()-1};await assert.rejects(h.functions.getCodeExecutionResult(h.request({runId:r.runId,resultToken:r.resultToken})),e=>e.code==='not-found');}));
test('invalid endpoint/key never calls provider and health exposes only invalid flag',async()=>{let calls=0;const h=harness({env:{JUDGE0_BASE_URL:'http://169.254.169.254',JUDGE0_API_KEY:'PRIVATE'},fetchImpl:async()=>{calls++;}});await assert.rejects(h.functions.submitCodeExecution(h.request()),deny);const health=await h.functions.getPlatformHealth();assert.equal(health.services.codeRunner,false);assert(!JSON.stringify(health).includes('PRIVATE'));assert.equal(calls,0);});

test('application-owned production AST has no eval/Function/vm/OS process/dynamic module sink',()=>{const {execFileSync}=require('node:child_process');const output=execFileSync(process.execPath,[path.join(__dirname,'code-execution-inventory.js')],{encoding:'utf8'});const inventory=JSON.parse(output);assert.deepEqual(inventory.production,[]);});
for(const [label,language,source,status]of [
 ['loop','javascript','while(true){}',5],
 ['sleep','python','import time; time.sleep(999)',5],
 ['memory','python','x = bytearray(10**10)',12],
 ['output','python','while True: print("output")',5],
 ['process storm','c','#include <unistd.h>\nint main(){for(int i=0;i<260;i++)if(fork()==0){sleep(3);_exit(0);}return 0;}',12],
 ['thread storm','java','class Main {public static void main(String[] x){for(int i=0;i<1024;i++)new Thread(()->{try{Thread.sleep(1000);}catch(Exception e){}}).start();}}',12]
])test('isolated mock resource outcome '+label+' never executes source in Functions',async()=>withProvider({result:{...accepted,status:{id:status,description:status===5?'Time Limit Exceeded':'Runtime Error'}}},async(h,p)=>{const r=await h.functions.submitCodeExecution(h.request({language,sourceCode:source}));assert.equal(r.status,status===5?'Time Limit Exceeded':'Runtime Error');assert.equal(p.requests.find(x=>x.method==='POST').body.source_code,source);assert(p.requests.find(x=>x.method==='POST').body.max_processes_and_or_threads<=256);}));

test('provider/parser/transport errors never echo secrets, raw body, URL or header values',async()=>{for(const message of ['PHASE23_FAKE_KEY judge0-submit-503','', 'https://private.invalid/secret']){const h=harness({env:{JUDGE0_API_KEY:'PHASE23_FAKE_KEY'},fetchImpl:async()=>{throw new Error(message);}});await assert.rejects(h.functions.submitCodeExecution(h.request()),e=>e.code==='unavailable'&&!e.message.includes('PHASE23_FAKE_KEY')&&!e.message.includes('private.invalid'));}});
test('trusted proxy hops select from the right; leftmost spoof and missing-peer ownership never become auth',()=>{const {requestIp}=require('../functions/lib/request-ip');const r={rawRequest:{socket:{remoteAddress:'10.0.0.1'},headers:{'x-forwarded-for':'attacker, 198.51.100.7, 10.0.0.2'}}};assert.equal(requestIp(r,{}),'10.0.0.1');assert.equal(requestIp(r,{TM_TRUSTED_PROXY_HOPS:'2'}),'198.51.100.7');assert.equal(requestIp({rawRequest:{headers:{'x-forwarded-for':'198.51.100.7'}}},{}),'unknown');});
