'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TM_PLAYWRIGHT_MODULE||'playwright-core');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
const source=fs.readFileSync(path.join(root,'assets/practical.js'),'utf8');
if(!source.includes('runJavascriptFallback'))throw new Error('Provide an extracted Phase 2.2 baseline root; current source has no local fallback.');
const csp=JSON.parse(fs.readFileSync(path.join(root,'vercel.json'))).headers.flatMap(x=>x.headers).find(x=>x.key==='Content-Security-Policy').value;
const html='<html><body><textarea id="codeEditor"></textarea><select id="codeLanguage"></select><textarea id="codeStdin"></textarea><pre id="codeOutput"></pre><button id="runCodeButton">run</button><button id="copyCodeButton"></button><button id="downloadCodeButton"></button><button id="clearCodeButton"></button><span id="runStatus"></span><span id="runTime"></span><span id="runMemory"></span><span id="runExit"></span><div id="toast"></div><script src="/assets/practical.js"></script></body></html>';
(async()=>{const browser=await chromium.launch({executablePath:process.env.TM_CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});const evidence={browser:browser.version(),cases:[]};try{
for(const withCSP of [true,false]){const page=await browser.newPage();let outbound=[];await page.addInitScript(()=>{const Original=Worker;window.__workers=0;window.Worker=class extends Original{constructor(...args){super(...args);window.__workers++;}};window.fetch=async()=>({ok:false,status:503,json:async()=>({error:{status:'UNAVAILABLE',message:'unavailable'}})});});
await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname==='/assets/practical.js')return r.fulfill({contentType:'application/javascript; charset=utf-8',body:source});if(u.pathname==='/probe'){outbound.push(u.searchParams.get('secret'));return r.fulfill({contentType:'text/event-stream',body:'data: test\n\n'});}return r.fulfill({contentType:'text/html; charset=utf-8',headers:withCSP?{'Content-Security-Policy':csp}:{},body:html});});await page.goto('http://127.0.0.1:19823/practical.html');await page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('tm-security-test',1);req.onupgradeneeded=()=>req.result.createObjectStore('secrets');req.onsuccess=()=>{const db=req.result,tx=db.transaction('secrets','readwrite');tx.objectStore('secrets').put('PHASE23_SECRET','secret');tx.oncomplete=()=>{db.close();resolve();};};req.onerror=()=>reject(req.error);}));
async function run(code){await page.selectOption('#codeLanguage','javascript');await page.fill('#codeEditor',code);await page.click('#runCodeButton');await page.waitForFunction(()=>!document.querySelector('#runCodeButton').disabled,{},{timeout:10000});return page.locator('#codeOutput').innerText();}
const apiCode="console.log(JSON.stringify(Object.fromEntries(['indexedDB','caches','BroadcastChannel','EventSource','SharedWorker','Worker','WebTransport','RTCPeerConnection','navigator','crypto','window','document','fetch','XMLHttpRequest','WebSocket','importScripts'].map(k=>[k,typeof globalThis[k]]))));";
await page.evaluate(async()=>{const c=await caches.open('tm-security-test');await c.put('/secret',new Response('PHASE23_CACHE_SECRET'));});
const apiOutput=await run(apiCode);
const leakCode="new Promise((resolve,reject)=>{const r=indexedDB.open('tm-security-test');r.onsuccess=()=>{const db=r.result,q=db.transaction('secrets').objectStore('secrets').get('secret');q.onsuccess=()=>{console.log(q.result);const es=new EventSource('http://127.0.0.1:19823/probe?secret='+encodeURIComponent(q.result));setTimeout(()=>{es.close();db.close();resolve('probe-done');},200);};};r.onerror=()=>reject(r.error);})";
const leakOutput=await run(leakCode);
const cacheOutput=await run("caches.open('tm-security-test').then(c=>c.match('http://127.0.0.1:19823/secret')).then(r=>r.text()).then(v=>console.log(v))");
let timeoutOutput=withCSP?'CSP prevents eval before loop':await run('while(true){}');
evidence.cases.push({withCSP,apiOutput,leakOutput,cacheOutput,outbound,timeoutOutput,workers:await page.evaluate(()=>window.__workers)});if(withCSP)assert(/unsafe-eval|Content Security Policy|EvalError/i.test(apiOutput));else{assert(leakOutput.includes('PHASE23_SECRET'));assert(cacheOutput.includes('PHASE23_CACHE_SECRET'));assert(outbound.includes('PHASE23_SECRET'));assert(/مؤقت|مهلة|تعذر/.test(timeoutOutput));}await page.close();}
fs.writeFileSync(path.join(__dirname,'../reports/phase23-baseline-browser.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
