'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.TM_PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..');let browser;
test.before(async()=>{browser=await chromium.launch({executablePath:process.env.TM_CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});});test.after(async()=>browser?.close());
async function exam(mode='success',expired=false){
 const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();page.on('dialog',d=>d.accept());
 await page.route('**/*',r=>{const u=new URL(r.request().url()),file=path.resolve(root,u.pathname.slice(1));if(u.hostname!=='exam.test'||!file.startsWith(root+'/')||!fs.existsSync(file)||/firebase-(sync|config)/.test(file))return r.abort();r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'image/png'});});
 await page.goto('https://exam.test/exams.html');await page.waitForFunction(()=>typeof window.startExam==='function');
 await page.evaluate(({mode,expired})=>{
  window.__calls=0;window.__commits=0;window.__savedId=null;window.__expiry=Date.now()+(expired?1400:60000);window.__start=Date.now();
  currentExamStudent={studentCode:'12345678',name:'Synthetic student',examAttempts:[]};currentSecureExams=[{id:'e',title:'Exam',duration:1}];
  window.MFCloud={ready:true,startSecureExam:async()=>({sessionId:'attempt-one',questions:[{type:'mcq',question:'Q',mark:1,options:['yes','no']}],exam:currentSecureExams[0],startedAt:new Date(__start).toISOString(),expiresAt:__expiry,serverNow:Date.now(),draft:{answers:{0:'0'}}}),saveSecureExamProgress:async()=>({saved:true,serverNow:Date.now()}),submitSecureExam:async()=>{window.__calls++;if(mode==='network'&&__calls===1)throw {code:'unavailable'};if(mode==='lost'&&__calls===1){__commits=1;throw {code:'request-timeout'};}if(mode==='invalid')return undefined;if(!__commits)__commits=1;return {id:'committed',examId:'e',examTitle:'Exam',score:1,maxScore:1,status:'submitted',submittedAt:new Date().toISOString()};}};
 },{mode,expired});
 await page.evaluate(()=>startExam('e','12345678'));await page.waitForSelector('#examSubmitBtn');return {context,page};
}
test('working student: loading then confirmed result, exact attempt draft cleared',async()=>{const f=await exam();try{
 await f.page.evaluate(()=>{const fn=MFCloud.submitSecureExam;MFCloud.submitSecureExam=async(...a)=>{await new Promise(r=>setTimeout(r,150));return fn(...a);};});await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>document.querySelector('#examSubmitBtn')?.classList.contains('is-loading'));await f.page.waitForFunction(()=>!document.body.classList.contains('exam-open'));assert.equal(await f.page.evaluate(()=>currentExamStudent.examAttempts[0].id),'committed');assert.equal(await f.page.evaluate(()=>readExamDraft('e','12345678')),null);
 }finally{await f.context.close();}});
test('affected student: network failure preserves draft, live timer runs, manual retry succeeds',async()=>{const f=await exam('network');try{
 await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>__calls===1&&!document.querySelector('#examSubmitBtn').disabled);assert.equal(await f.page.evaluate(()=>readExamDraft('e','12345678').answers[0]),'0');const before=await f.page.locator('#examTimer b').textContent();await f.page.waitForFunction(text=>document.querySelector('#examTimer b').textContent!==text,before);await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>!document.body.classList.contains('exam-open'));assert.equal(await f.page.evaluate(()=>__commits),1);
 }finally{await f.context.close();}});
test('lost response: retry displays existing committed result once',async()=>{const f=await exam('lost');try{await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>__calls===1&&!document.querySelector('#examSubmitBtn').disabled);await f.page.waitForFunction(()=>Date.now()>=Number(document.querySelector('#liveExamForm').dataset.tmSubmitLockedUntil||0));await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>!document.body.classList.contains('exam-open'));assert.equal(await f.page.evaluate(()=>__commits),1);assert.equal(await f.page.evaluate(()=>currentExamStudent.examAttempts.length),1);}finally{await f.context.close();}});
test('expired failed request: answers locked, no automatic retry loop, explicit retry succeeds',async()=>{const f=await exam('network',true);try{await f.page.waitForFunction(()=>__calls===1&&!document.querySelector('#examSubmitBtn').disabled);assert(await f.page.locator('#liveExamForm input').first().isDisabled());await f.page.waitForTimeout(8500);assert.equal(await f.page.evaluate(()=>__calls),1);await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>!document.body.classList.contains('exam-open'));}finally{await f.context.close();}});
test('malformed response never displays success or clears answers',async()=>{const f=await exam('invalid');try{await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>__calls===1&&!document.querySelector('#examSubmitBtn').disabled);assert(await f.page.locator('#examSubmitBtn').isVisible());assert.equal(await f.page.evaluate(()=>currentExamStudent.examAttempts.length),0);assert(await f.page.evaluate(()=>!!readExamDraft('e','12345678')));}finally{await f.context.close();}});
test('post-confirmation rendering failure cannot misrepresent committed submit as failed',async()=>{const f=await exam();try{await f.page.evaluate(()=>{renderExamPortal=()=>{throw Error('renderer failed');};});await f.page.click('#examSubmitBtn');await f.page.waitForFunction(()=>!document.body.classList.contains('exam-open'));assert.match(await f.page.locator('#toast').textContent(),/تم تسليم الامتحان وحفظ النتيجة/);assert.equal(await f.page.evaluate(()=>__commits),1);}finally{await f.context.close();}});
