'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),s=require('./testing/security-emulator'),{createAdminDOM,tick}=require('./testing/admin-dom'),{payloads,assertInert}=require('./testing/xss-payloads');let tokens,ui;const p=payloads[0];
test.before(async()=>{tokens=await s.seed();ui=await createAdminDOM();ui.window.__tmXss=0;await s.db.doc('students/'+s.code).update({contentAccessMode:'full'});});test.after(()=>ui?.close());const check=()=>assertInert(assert,ui.document.getElementById('adminContent'),ui.window);
test('public booking callable -> Firestore raw record -> actual Admin renderer is inert',async()=>{const result=await s.call('createBooking',{name:p,studentPhone:'01012345678',parentPhone:'01087654321',grade:s.grade,month:'سبتمبر',academicYear:'2026/2027',term:'الترم الأول',requestId:'xss-booking-request-001'});const doc=await s.db.doc('bookings/'+result.code).get();assert(doc.exists);assert.equal(doc.data().name,p);assert(/^[A-Z0-9_-]+$/.test(doc.id));ui.window.__rows=[doc.data()];ui.run('adminData.bookings=__rows;renderBookings()');check();assert(ui.document.getElementById('adminContent').textContent.includes(p));});
test('public review callable -> actual moderation/approval renderer -> approved Firestore/public homepage keeps text',async()=>{assert((await s.call('createReview',{name:p,role:p,text:p,rating:5})).ok);const docs=await s.db.collection('reviews').where('text','==',p).get();assert.equal(docs.size,1);const doc=docs.docs[0];assert.equal(doc.data().text,p);ui.window.__rows=[{...doc.data(),id:doc.id}];ui.run('adminData.reviews=__rows;renderReviewsAdmin()');check();
// Review saveContent uses Firestore directly; replace only that adapter with a local emulator persistence fixture.
ui.window.MFCloud.saveContent=async(collection,row)=>{assert.equal(collection,'reviews');await doc.ref.update({approved:row.approved});};await ui.window.approveReview(doc.id);const published=await doc.ref.get();assert.equal(published.data().approved,true);check();ui.window.__rows=[published.data()];ui.run('appData.reviews=__rows');const box=ui.document.createElement('section');box.id='reviewsList';ui.document.body.appendChild(box);ui.window.renderReviews();assertInert(assert,box,ui.window);assert(box.textContent.includes(p));});
test('public error callable -> persisted message/page/userAgent -> actual Admin viewer is inert',async()=>{await s.call('reportClientError',{message:p,page:p,userAgent:p});const docs=await s.db.collection('client_errors').get();const row=docs.docs.find(d=>d.data().message===p);assert(row);assert.equal(row.data().userAgent,p);ui.window.MFCloud.getClientErrors=async()=>[{id:row.id,...row.data()}];await ui.run("adminSections.push(['errors','database','errors']);currentSection='errors';renderSection()");check();assert(ui.document.getElementById('clientErrorsBox').textContent.includes(p));});
test('homework essay/code actual callable -> raw answers persisted -> actual correction renderer is inert',async()=>{for(const type of['essay','code']){const assignmentId='xss-'+type;await s.db.doc('assignments/'+assignmentId).set({title:p,grade:s.grade,published:true,active:true,totalScore:1,questions:[{type,question:p,mark:1,modelAnswer:p}]});assert((await s.call('submitAssignmentAnswer',s.portal(tokens.token,s.code,{assignmentId,answers:{0:p}}))).ok);const docs=await s.db.collection('homework_submissions').where('assignmentId','==',assignmentId).get();assert.equal(docs.size,1);const row={id:docs.docs[0].id,...docs.docs[0].data()};assert.equal(row.answers[0].answer,p);ui.window.__st={studentCode:s.code,name:'test',grade:s.grade,active:true,homeworks:[row]};ui.window.__assignment={id:assignmentId,...(await s.db.doc('assignments/'+assignmentId).get()).data()};ui.run('adminData.students=[__st];adminData.assignments=[__assignment];renderAssignments()');ui.window.openHomeworkAdminFile(assignmentId);await tick();assert(ui.document.querySelector('.assignment-submission-row'));check();assert(ui.document.getElementById('adminContent').textContent.includes(p));}});
test('exam essay/code actual start/save/submit -> raw persisted answers -> actual correction renderer is inert',async()=>{await s.db.doc('exams/xss-exam').set({title:p,grade:s.grade,active:true,published:true,duration:20,totalScore:2,text:'Explain\nType: essay\nMark: 1\nAnswer: model\n\nWrite code\nType: code\nMark: 1\nAnswer: model',openAt:new Date(Date.now()-10000).toISOString(),closeAt:new Date(Date.now()+3600000).toISOString()});const started=await s.call('startExam',s.portal(tokens.token,s.code,{examId:'xss-exam'}));await s.call('saveExamProgress',s.portal(tokens.token,s.code,{sessionId:started.sessionId,revision:1,answers:{0:p,1:p}}));await s.call('submitExam',s.portal(tokens.token,s.code,{sessionId:started.sessionId,answers:{0:p,1:p}}));const docs=await s.db.collection('exam_attempts').where('examId','==','xss-exam').get();assert.equal(docs.size,1);const attempt={id:docs.docs[0].id,...docs.docs[0].data()};assert.equal(attempt.answers.length,2);for(const a of attempt.answers)assert.equal(a.answer,p);ui.window.__attempt=attempt;ui.run('adminData.examAttempts=[__attempt]');ui.window.correctAttempt(attempt.id);const root=ui.document.querySelector('.correction-modal-v40');assertInert(assert,root,ui.window);assert(root.textContent.includes(p));ui.window.closeCorrectionModal();});
test('raw malicious filename after server immutable registration remains inert in actual attachment renderer',async()=>{const bytes=Buffer.from('%PDF-fixture'),fileName='"><svg onload="globalThis.__tmXss=1">.pdf';const permit=await s.call('prepareHomeworkUpload',s.portal(tokens.token,s.code,{fileName,size:bytes.length,contentType:'application/pdf'}));
// Seed staged bytes with the Admin SDK; existing Phase 2.1 suite separately exercises client Storage upload rules.
await s.admin.storage().bucket().file(permit.path).save(bytes,{metadata:{contentType:'application/pdf'}});const registered=await s.call('registerHomeworkSubmission',s.portal(tokens.token,s.code,{uploadId:permit.uploadId,path:permit.path,fileName}));const row=(await s.db.doc('homework_submissions/'+registered.id).get()).data();assert.equal(row.fileName,fileName);const host=ui.document.createElement('section');host.innerHTML=ui.window.resourceCard({id:registered.id,title:row.fileName,fileUrl:row.fileUrl,fileName:row.fileName},'material');assertInert(assert,host,ui.window);assert(host.textContent.includes(fileName));assert(/^https:\/\//.test(host.querySelector('a').href));});
